---
title: Rem gebruiken voor formaten
hero_image: images/banner.png
description: Rem gebruiken voor formaten in CSS.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Rem gebruiken voor formaten
