---
title: Utiliser rem pour les tailles
hero_image: images/banner.png
description: Utilise rem pour les tailles en CSS.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Utiliser rem pour les tailles
